name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh sast

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh sca

  iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh iac
